spring:
  application:
    name: family-finance
  datasource:
    url: jdbc:mysql://localhost:3306/family_finance?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect